name: arkademi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  freezed: ^2.4.5
  google_fonts: ^5.1.0
  video_player: ^2.8.1
  syncfusion_flutter_gauges: ^23.2.6
  dio: ^5.3.4
  flutter_lints: ^2.0.0
  html_unescape: ^2.0.0
  path_provider: ^2.0.2
  permission_handler: ^8.0.0+2
  open_file_plus: ^3.4.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  
  build_runner: ^2.4.6
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

